apiVersion: v1
kind: ConfigMap
metadata:
  name: pghero
data:
  pghero.yml: |-
    databases:
      mydatabase1:
        url: "postgres://postgres:postgres@192.168.215.2:5432/mydatabase1"

      # Add more databases
      mydatabase2:
        url: postgres://postgres:postgres@192.168.215.2:5432/mydatabase2
      mydatabase3:
        url: postgres://postgres:postgres@192.168.215.2:5432/mydatabase3

    # Minimum time for long running queries
    # long_running_query_sec: 60

    # Minimum average time for slow queries
    # slow_query_ms: 20

    # Minimum calls for slow queries
    # slow_query_calls: 100

    # Minimum connections for high connections warning
    # total_connections_threshold: 500

    # Explain functionality
    # explain: true / false / analyze

    # Statement timeout for explain
    # explain_timeout_sec: 10

    # Visualize URL for explain
    #  visualize_url: https://0.0.0.0:3000

    # Time zone
    # time_zone: "Pacific Time (US & Canada)"