apiVersion: v1
kind: Service
metadata:
  name: {{ include "pghero.fullname" . }}
  labels:
    {{- include "pghero.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "pghero.selectorLabels" . | nindent 4 }}
